name: deep_water
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - cartopy
  - metpy
  - rasterio
  - rioxarray
  - holoviews
  - seaborn
  - pandas
  - ctd
  - pathlib
  - plotly
  - pip:
    - cmcrameri==1.5
    - contourpy==1.0.7
    - dask==2023.1.1
    - dmi-open-data==0.1.2
    - matplotlib==3.7.1
    - metpy==1.4.0
    - multidict==6.0.4
    - netcdf4==1.5.8
    - numpy==1.24.3
    - openpyxl==3.1.1
    - plotly==5.14.1
    - pytides==0.0.4
    - pytides2==0.0.5
    - rasterio==1.3.5
    - rioxarray==0.13.3
    - scipy==1.9.3
    - unisacsi==0.2.1
    - windrose==1.8.1
    - xhistogram==0.3.2
    - datetime

