name: deep_water
channels: 
  - conda-forge
dependencies:
  - python==3.10
  - xarray==2023.1.0
  - netcdf4==1.6.2
  - cartopy==0.21.1
  - metpy==1.5.1
  - ctd==1.4.4
  - geopy==2.4.0
  - seaborn==0.13.0
  
