name: deep_water
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - cartopy
  - metpy
  - seaborn
  - pandas
  - ctd
  - pathlib
  - datetime
  - importlib
  - geopy
  - os
